apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: listener-agent
  namespace: canarytrace
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: listener
            image: quay.io/canarytrace/listener-agent:1.9
            env:
            - name: ENV_PRINT
              value: 'no'
            - name: TAGS
              value: 'monitoring;production'
            - name: ELASTIC_CLUSTER
              value: "XXXX"
            - name: ELASTIC_HTTP_AUTH
              value: "elastic:XXXX"
            - name: KIBANA_ENDPOINT
              value: "XXXX"
            - name: SLACK_WEBHOOK_URL_INTERNAL
              value: "XXXX"
            - name: SLACK_WEBHOOK_URL
              value: "XXXX"
            - name: EMAIL_SMTP_SERVER
              value: "smtp.ethereal.email"
            - name: EMAIL_SMTP_PORT
              value: "587"
            - name: EMAIL_SMTP_USER
              value: "XXXX"
            - name: EMAIL_SMTP_PASS
              value: "XXXX"
            resources:
              requests:
                memory: "50Mi"
                cpu: "50m"
              limits:
                memory: "300Mi"
                cpu: "200m"
            imagePullPolicy: "IfNotPresent"
            volumeMounts:
              - name: config-rules
                mountPath: /opt/canary-listener/rules/internal.yaml
                subPath: rules
                readOnly: true
          restartPolicy: "Never"
          volumes:
            - name: canarytrace-secret
              secret:
                secretName: secret
            - name: config-rules
              configMap:
                name: listener-agent-rules
                items:
                  - key: rules
                    path: rules
