apiVersion: v1
kind: ConfigMap
metadata:
  name: listener-agent-rules
  namespace: canarytrace
data:
  rules: |
    rules:
    - type: match
      title: "Failed check your page!"
      index: c.report
      field: passed
      operator: must
      expected: false
      min: 2
      reportLabels:
      - 'fullTitle'
      - 'timestamp'
      reporters:
      - type: slack
        score: 10
        message: "An error occurred while checking."
    - type: contains
      title: "Response with Javascript must contains gzip or brotli compression."
      index: c.request-log
      field: response.headers.content-type
      value: 'javascript'
      expression:
        field: 'response.headers.content-encoding'
        operator: must_not
        values:
        - 'gzip'
        - 'br'
      min: 10
      reportLabels:
      - 'url'
      - 'timestamp'
      reporters:
      - type: slack
        score: 40
        message: "Use Brotli for plain text compression."
    - type: contains
      title: "Responses with CSS files must contains gzip or brotli compression."
      index: c.request-log
      field: response.headers.content-type
      value: 'css'
      expression:
        field: 'response.headers.content-encoding'
        operator: must_not
        values:
        - 'gzip'
        - 'br'
      min: 10
      reportLabels:
      - 'url'
      - 'timestamp'
      reporters:
      - type: slack
        score: 40
        message: "Use Brotli for plain text compression."
    - type: range
      title: "Higher response time."
      index: c.performance-entries
      field: responseTime
      operator: gte
      value: 3000
      min: 10
      reportLabels:
      - 'name'
      - 'responseTime'
      - 'timestamp'
      reporters:
      - type: slack
        score: 40
        message: "Some of responses has higher response time."
    - type: range
      title: "LCP Needs improvement (CoreWebVitals)"
      index: c.audit
      field: audits.largest-contentful-paint.numericValue
      operator: gte
      value: 2500
      min: 5
      reportLabels:
      - 'audits.largest-contentful-paint.numericValue'
      - 'timestamp'
      reporters:
      - type: slack
        score: 40
        message: "LCP reports the render time of the largest image or text block visible within the viewport, https://web.dev/lcp/"
    - type: range
      title: "LCP Poor (CoreWebVitals)"
      index: c.audit
      field: audits.largest-contentful-paint.numericValue
      operator: gte
      value: 4000
      min: 5
      reportLabels:
      - 'audits.largest-contentful-paint.numericValue'
      - 'timestamp'
      reporters:
      - type: slack
        score: 20
        message: "LCP reports the render time of the largest image or text block visible within the viewport, https://web.dev/lcp/"
    - type: range
      title: "TTI Needs improvement"
      index: c.audit
      field: audits.interactive.numericValue
      operator: gte
      value: 3900
      min: 5
      reportLabels:
      - 'audits.interactive.numericValue'
      - 'timestamp'
      reporters:
      - type: slack
        score: 40
        message: "How long it takes a page to become fully interactive, https://web.dev/tti/"
    - type: range
      title: "TTI Poor"
      index: c.audit
      field: audits.interactive.numericValue
      operator: gte
      value: 7300
      min: 5
      reportLabels:
      - 'audits.interactive.numericValue'
      - 'timestamp'
      reporters:
      - type: slack
        score: 20
        message: "How long it takes a page to become fully interactive, https://web.dev/tti/"
    - type: range
      title: "CLS Needs improvement (CoreWebVitals)"
      index: c.audit
      field: audits.cumulative-layout-shift.numericValue
      operator: gte
      value: 0.1
      min: 5
      reportLabels:
      - 'audits.cumulative-layout-shift.numericValue'
      - 'timestamp'
      reporters:
      - type: slack
        score: 40
        message: "User-centric metric for measuring visual stability, https://web.dev/cls/"
    - type: range
      title: "CLS Poor (CoreWebVitals)"
      index: c.audit
      field: audits.cumulative-layout-shift.numericValue
      operator: gte
      value: 0.25
      min: 5
      reportLabels:
      - 'audits.cumulative-layout-shift.numericValue'
      - 'timestamp'
      reporters:
      - type: slack
        score: 30
        message: "User-centric metric for measuring visual stability, https://web.dev/cls/"
    - type: range
      title: "Load time needs improvement"
      index: c.performance-entries
      field: loadEventEnd
      operator: gte
      value: 3000
      min: 5
      reportLabels:
      - 'loadEventEnd'
      - 'timestamp'
      reporters:
      - type: slack
        score: 40
        message: "Page is complete loaded."
    - type: range
      title: "Load time poor"
      index: c.performance-entries
      field: loadEventEnd
      operator: gte
      value: 5000
      min: 5
      reportLabels:
      - 'loadEventEnd'
      - 'timestamp'
      reporters:
      - type: slack
        score: 20
        message: "Page is complete loaded."
